import type { AppState } from "./types";

/** Senhas demo: ver README implícito — participante Maria `Capacita@2026`, admin `Admin@2026!`, instrutor `Instrutor@2026` */
const HASH_PART = "35e18a528b6c7035e6b198713fe16aedd4a59a7c7529e654d96fc50c5217778a";
const HASH_ADMIN = "f0ce0e86206541c60bc47be815f83eba98004f63c883e6d71ff5cc929cb5f9ca";
const HASH_INST = "c588527645db64369ea1e178c14bd8aa11862aa9534edc10517f5931aff285b9";

export function createInitialState(): AppState {
  const now = new Date().toISOString();
  return {
    secretariats: [
      { id: "sec-geral", name: "Secretaria de Administração", code: "SEMAD" },
      { id: "sec-saude", name: "Secretaria Municipal de Saúde", code: "SMS" },
      { id: "sec-edu", name: "Secretaria Municipal de Educação", code: "SME" },
      { id: "sec-gov", name: "Secretaria de Governo", code: "SEGOV" },
    ],
    users: [
      {
        id: "u-maria",
        registrationNumber: "2024001",
        cpf: "12345678900",
        fullName: "Maria da Silva",
        email: "maria.silva@prefeitura.gov",
        phone: "(11) 99999-0001",
        secretariatId: "sec-geral",
        role: "participante",
        passwordHash: HASH_PART,
        firstAccessCompleted: true,
        birthDate: "1988-03-15",
        managedSecretariatIds: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "u-jose",
        registrationNumber: "2024002",
        cpf: "98765432100",
        fullName: "José Pereira",
        email: "jose.pereira@prefeitura.gov",
        secretariatId: "sec-edu",
        role: "participante",
        passwordHash: null,
        firstAccessCompleted: false,
        birthDate: "1990-07-22",
        managedSecretariatIds: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "u-ana",
        registrationNumber: "2024003",
        cpf: "45678912300",
        fullName: "Ana Rodrigues",
        email: "ana.rodrigues@prefeitura.gov",
        secretariatId: "sec-saude",
        role: "participante",
        passwordHash: HASH_PART,
        firstAccessCompleted: true,
        birthDate: "1992-11-01",
        managedSecretariatIds: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "u-carlos",
        registrationNumber: "500100",
        cpf: "11122233344",
        fullName: "Carlos Mendes",
        email: "carlos.mendes@prefeitura.gov",
        secretariatId: "sec-edu",
        role: "instrutor",
        passwordHash: HASH_INST,
        firstAccessCompleted: true,
        birthDate: "1980-05-10",
        managedSecretariatIds: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "u-gestor",
        registrationNumber: "900200",
        cpf: "22233344455",
        fullName: "Fernanda Costa",
        email: "fernanda.costa@prefeitura.gov",
        secretariatId: "sec-saude",
        role: "gestor",
        passwordHash: HASH_ADMIN,
        firstAccessCompleted: true,
        birthDate: "1985-01-30",
        managedSecretariatIds: ["sec-saude"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "u-admin",
        registrationNumber: "900100",
        cpf: "33344455566",
        fullName: "João Martins",
        email: "joao.martins@prefeitura.gov",
        secretariatId: "sec-gov",
        role: "admin_programa",
        passwordHash: HASH_ADMIN,
        firstAccessCompleted: true,
        birthDate: "1978-09-12",
        managedSecretariatIds: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "u-ti",
        registrationNumber: "900001",
        cpf: "44455566677",
        fullName: "Equipe TI",
        email: "ti@prefeitura.gov",
        secretariatId: "sec-gov",
        role: "admin_tecnico",
        passwordHash: HASH_ADMIN,
        firstAccessCompleted: true,
        birthDate: "1983-04-04",
        managedSecretariatIds: [],
        createdAt: now,
        updatedAt: now,
      },
    ],
    instructors: [
      {
        id: "ins-1",
        userId: "u-carlos",
        fullName: "Carlos Mendes",
        cpf: "11122233344",
        email: "carlos.mendes@prefeitura.gov",
        specialty: "Informática aplicada",
        createdAt: now,
      },
      {
        id: "ins-2",
        userId: null,
        fullName: "Ana Paula Ferreira",
        cpf: "55566677788",
        email: "ana.ferreira@oab.gov",
        specialty: "Direito do consumidor",
        createdAt: now,
      },
      {
        id: "ins-3",
        userId: null,
        fullName: "Roberto Lima",
        cpf: "66677788899",
        email: "roberto.lima@email.br",
        specialty: "Empreendedorismo",
        createdAt: now,
      },
      {
        id: "ins-4",
        userId: null,
        fullName: "Marcos Oliveira",
        cpf: "77788899900",
        email: "marcos.oliveira@saude.gov",
        specialty: "Enfermagem — primeiros socorros",
        createdAt: now,
      },
      {
        id: "ins-5",
        userId: null,
        fullName: "Lucia Santos",
        cpf: "88899900011",
        email: "lucia.santos@email.br",
        specialty: "Educação financeira",
        createdAt: now,
      },
      {
        id: "ins-6",
        userId: null,
        fullName: "Fernanda Alves",
        cpf: "99900011122",
        email: "fernanda.alves@agr.br",
        specialty: "Eng. agrônoma",
        createdAt: now,
      },
    ],
    courses: [
      {
        id: "1",
        title: "Informática aplicada ao serviço público",
        description:
          "Capacitação introdutória em informática voltada a servidores e comissionados: produtividade, segurança da informação e uso responsável de sistemas internos.",
        category: "Tecnologia",
        modality: "presencial",
        workloadHours: 3,
        scheduleSummary: "Módulo único — manhã, com pausa institucional.",
        location: "Centro de Capacitação Municipal",
        spots: 40,
        enrollmentStart: "2026-04-01T00:00:00.000Z",
        enrollmentEnd: "2026-05-14T23:59:59.000Z",
        eligibilityCriteria: "Servidores e comissionados da administração direta.",
        minimumAttendancePercent: 75,
        requirements: ["Documento funcional ou identificação matriculada", "Termo LGPD interno"],
        status: "inscricoes_abertas",
        primaryInstructorId: "ins-1",
        designationDocumentId: null,
        displayDate: "2026-05-15",
        displayTimeRange: "09:00 - 12:00",
        ownerSecretariatId: "sec-edu",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "2",
        title: "Direitos do consumidor — oficina aplicada",
        description:
          "Oficina sobre defesa do consumidor com foco em atendimento ao cidadão nas unidades municipais.",
        category: "Cidadania",
        modality: "hibrido",
        workloadHours: 2,
        scheduleSummary: "Encontro síncrono remoto + atividade presencial opcional.",
        location: "Auditório da Prefeitura",
        spots: 100,
        enrollmentStart: "2026-04-01T00:00:00.000Z",
        enrollmentEnd: "2026-05-19T23:59:59.000Z",
        eligibilityCriteria: "Servidores em atendimento ao público.",
        minimumAttendancePercent: 80,
        requirements: ["Identificação funcional"],
        status: "inscricoes_abertas",
        primaryInstructorId: "ins-2",
        designationDocumentId: null,
        displayDate: "2026-05-20",
        displayTimeRange: "14:00 - 16:00",
        ownerSecretariatId: "sec-gov",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "3",
        title: "Empreendedorismo e inovação na gestão municipal",
        description: "Planejamento de pequenos projetos e parcerias com desenvolvimento econômico local.",
        category: "Gestão",
        modality: "presencial",
        workloadHours: 8,
        scheduleSummary: "Carga horária integral com laboratório de ideias.",
        location: "Sala de Treinamento — Secretaria de Desenvolvimento",
        spots: 30,
        enrollmentStart: "2026-03-01T00:00:00.000Z",
        enrollmentEnd: "2026-04-01T23:59:59.000Z",
        eligibilityCriteria: "Gestores e analistas das secretarias parceiras.",
        minimumAttendancePercent: 75,
        requirements: ["Alinhamento com chefia imediata"],
        status: "em_execucao",
        primaryInstructorId: "ins-3",
        designationDocumentId: null,
        displayDate: "2026-05-25",
        displayTimeRange: "08:00 - 17:00",
        ownerSecretariatId: "sec-gov",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "4",
        title: "Primeiros socorros no ambiente de trabalho",
        description: "Protocolos básicos de atendimento emergencial para equipes de campo e unidades.",
        category: "Saúde",
        modality: "presencial",
        workloadHours: 4,
        scheduleSummary: "Teoria e prática em estação de simulação.",
        location: "Unidade de Saúde Central",
        spots: 25,
        enrollmentStart: "2026-04-10T00:00:00.000Z",
        enrollmentEnd: "2026-05-30T23:59:59.000Z",
        eligibilityCriteria: "Servidores da rede municipal de saúde e apoio.",
        minimumAttendancePercent: 85,
        requirements: ["Declaração de saúde ocupacional"],
        status: "inscricoes_abertas",
        primaryInstructorId: "ins-4",
        designationDocumentId: null,
        displayDate: "2026-06-01",
        displayTimeRange: "09:00 - 13:00",
        ownerSecretariatId: "sec-saude",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "5",
        title: "Educação financeira para servidores",
        description: "Orçamento familiar, benefícios e planejamento de longo prazo.",
        category: "Finanças",
        modality: "online",
        workloadHours: 2,
        scheduleSummary: "Sessão única à noite, plataforma interna.",
        location: "Plataforma interna — link no mural do curso",
        spots: 50,
        enrollmentStart: "2026-04-01T00:00:00.000Z",
        enrollmentEnd: "2026-06-09T23:59:59.000Z",
        eligibilityCriteria: "Todos os vínculos estáveis com a prefeitura.",
        minimumAttendancePercent: 100,
        requirements: ["Confirmação de vínculo"],
        status: "inscricoes_abertas",
        primaryInstructorId: "ins-5",
        designationDocumentId: null,
        displayDate: "2026-06-10",
        displayTimeRange: "19:00 - 21:00",
        ownerSecretariatId: "sec-geral",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "6",
        title: "Horta urbana e sustentabilidade",
        description: "Práticas de hortas comunitárias em espaços públicos municipais.",
        category: "Meio Ambiente",
        modality: "presencial",
        workloadHours: 4,
        scheduleSummary: "Atividade de campo supervisionada.",
        location: "Parque Municipal",
        spots: 20,
        enrollmentStart: "2026-01-01T00:00:00.000Z",
        enrollmentEnd: "2026-04-09T23:59:59.000Z",
        eligibilityCriteria: "Servidores interessados em projetos ambientais.",
        minimumAttendancePercent: 75,
        requirements: ["EPI indicado no edital interno"],
        status: "encerrado",
        primaryInstructorId: "ins-6",
        designationDocumentId: null,
        displayDate: "2026-04-10",
        displayTimeRange: "08:00 - 12:00",
        ownerSecretariatId: "sec-gov",
        createdAt: now,
        updatedAt: now,
      },
    ],
    sessions: [
      { id: "sess-1-1", courseId: "1", label: "Turno manhã", date: "2026-05-15", startTime: "09:00", endTime: "12:00" },
      { id: "sess-2-1", courseId: "2", label: "Turno tarde", date: "2026-05-20", startTime: "14:00", endTime: "16:00" },
      { id: "sess-3-1", courseId: "3", label: "Dia integral", date: "2026-05-25", startTime: "08:00", endTime: "17:00" },
      { id: "sess-4-1", courseId: "4", label: "Manhã", date: "2026-06-01", startTime: "09:00", endTime: "13:00" },
      { id: "sess-5-1", courseId: "5", label: "Noite", date: "2026-06-10", startTime: "19:00", endTime: "21:00" },
      { id: "sess-6-1", courseId: "6", label: "Campo", date: "2026-04-10", startTime: "08:00", endTime: "12:00" },
    ],
    enrollments: [
      {
        id: "ENR001",
        courseId: "1",
        participantId: "u-maria",
        status: "confirmada",
        submittedAt: "2026-04-20T10:30:00.000Z",
        reviewedAt: "2026-04-21T14:00:00.000Z",
        reviewedByUserId: "u-admin",
        documents: [
          { name: "Identificação.pdf", status: "aprovado" },
          { name: "Termo_LGPD.pdf", status: "aprovado" },
        ],
        qrToken: "QR-ENR001-1",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "ENR002",
        courseId: "2",
        participantId: "u-maria",
        status: "recebida",
        submittedAt: "2026-04-22T09:15:00.000Z",
        documents: [{ name: "Identificação.pdf", status: "pendente" }],
        qrToken: "QR-ENR002-2",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "ENR003",
        courseId: "6",
        participantId: "u-maria",
        status: "confirmada",
        submittedAt: "2026-03-15T11:00:00.000Z",
        reviewedAt: "2026-03-16T09:00:00.000Z",
        reviewedByUserId: "u-gestor",
        documents: [{ name: "Identificação.pdf", status: "aprovado" }],
        qrToken: "QR-ENR003-6",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "ENR004",
        courseId: "3",
        participantId: "u-jose",
        status: "em_validacao",
        submittedAt: "2026-04-18T16:45:00.000Z",
        reviewedAt: "2026-04-19T10:00:00.000Z",
        reviewedByUserId: "u-admin",
        documents: [
          { name: "Alinhamento_chefia.pdf", status: "aprovado" },
          { name: "Complemento.pdf", status: "rejeitado" },
        ],
        qrToken: "QR-ENR004-3",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "ENR005",
        courseId: "4",
        participantId: "u-ana",
        status: "em_validacao",
        submittedAt: "2026-04-23T08:30:00.000Z",
        documents: [
          { name: "Identificação.pdf", status: "pendente" },
          { name: "Declaracao_Saude.pdf", status: "pendente" },
        ],
        qrToken: "QR-ENR005-4",
        createdAt: now,
        updatedAt: now,
      },
    ],
    attendance: [
      {
        id: "att-003-6",
        enrollmentId: "ENR003",
        sessionId: "sess-6-1",
        checkInAt: "2026-04-10T08:05:00.000Z",
        checkOutAt: "2026-04-10T11:58:00.000Z",
        status: "presente",
        manualAdjustment: false,
      },
    ],
    certificates: [
      {
        id: "CERT-1",
        enrollmentId: "ENR003",
        code: "CERT-2026-ENR003-HCU",
        issuedAt: "2026-04-11T10:00:00.000Z",
        courseTitleSnapshot: "Horta urbana e sustentabilidade",
        participantNameSnapshot: "Maria da Silva",
        workloadHoursSnapshot: 4,
      },
    ],
    documents: [],
    audit: [],
  };
}
