export const ROUTES = {
  access: {
    login: "/acesso/entrar",
    firstAccess: "/acesso/primeiro-acesso",
    forgot: "/acesso/recuperar-senha",
    reset: "/acesso/redefinir-senha",
    denied: "/acesso/negado",
    sessionExpired: "/acesso/sessao-expirada",
  },
  portal: {
    home: "/portal",
    courses: "/portal/cursos",
    course: (id: string) => `/portal/cursos/${id}`,
    enroll: (id: string) => `/portal/cursos/${id}/inscricao`,
    enrollments: "/portal/inscricoes",
    enrollment: (id: string) => `/portal/inscricoes/${id}`,
    attendance: (id: string) => `/portal/inscricoes/${id}/presenca`,
    qrcode: (id: string) => `/portal/inscricoes/${id}/qrcode`,
    certificates: "/portal/certificados",
    certificate: (enrollmentId: string) => `/portal/certificados/${enrollmentId}`,
    history: "/portal/historico",
    profile: "/portal/perfil",
  },
  instructor: {
    home: "/instrutor",
    courses: "/instrutor/cursos",
    course: (id: string) => `/instrutor/cursos/${id}`,
    participants: (id: string) => `/instrutor/cursos/${id}/participantes`,
    document: (id: string) => `/instrutor/cursos/${id}/documento`,
    attendance: (id: string) => `/instrutor/cursos/${id}/presenca`,
    profile: "/instrutor/perfil",
  },
  admin: {
    root: "/admin",
    courses: "/admin/cursos",
    courseNew: "/admin/cursos/novo",
    course: (id: string) => `/admin/cursos/${id}`,
    courseEdit: (id: string) => `/admin/cursos/${id}/editar`,
    instructors: "/admin/instrutores",
    instructor: (id: string) => `/admin/instrutores/${id}`,
    enrollments: "/admin/inscricoes",
    enrollment: (id: string) => `/admin/inscricoes/${id}`,
    validation: "/admin/validacao",
    attendance: "/admin/presenca",
    certificates: "/admin/certificados",
    reports: "/admin/relatorios",
    settings: "/admin/configuracoes",
    users: "/admin/usuarios",
  },
} as const;

/** Redirecionamentos da base Lovable */
export const LEGACY_REDIRECTS: Record<string, string> = {
  "/login": "/acesso/entrar",
  "/cadastro": "/acesso/primeiro-acesso",
  "/": "/acesso/entrar",
  "/cursos": "/portal/cursos",
  "/minhas-inscricoes": "/portal/inscricoes",
  "/certificados": "/portal/certificados",
};
